#!/bin/sh

# This script makes services start/stop when a machine gets or loses AC
# power. On battery: stop service. On AC: start service

SERVICE_NAME=`basename $0`
SERVICE_NAME=${0##*/}

case $1 in
    false)
        service $SERVICE_NAME start || :
        ;;
    true)
        service $SERVICE_NAME stop || :
        ;;
esac
